// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// twice
double twice(double x);
RcppExport SEXP _einsum_twice(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(twice(x));
    return rcpp_result_gen;
END_RCPP
}
// einsum_impl_fast
NumericVector einsum_impl_fast(IntegerVector lengths_vec, ListOf<IntegerVector> array_vars_list, IntegerVector not_result_vars_vec, IntegerVector result_vars_vec, ListOf<NumericVector> arrays);
RcppExport SEXP _einsum_einsum_impl_fast(SEXP lengths_vecSEXP, SEXP array_vars_listSEXP, SEXP not_result_vars_vecSEXP, SEXP result_vars_vecSEXP, SEXP arraysSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type lengths_vec(lengths_vecSEXP);
    Rcpp::traits::input_parameter< ListOf<IntegerVector> >::type array_vars_list(array_vars_listSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type not_result_vars_vec(not_result_vars_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type result_vars_vec(result_vars_vecSEXP);
    Rcpp::traits::input_parameter< ListOf<NumericVector> >::type arrays(arraysSEXP);
    rcpp_result_gen = Rcpp::wrap(einsum_impl_fast(lengths_vec, array_vars_list, not_result_vars_vec, result_vars_vec, arrays));
    return rcpp_result_gen;
END_RCPP
}
// mat_mult
NumericVector mat_mult(NumericVector mat1, NumericVector mat2, int I, int J, int K);
RcppExport SEXP _einsum_mat_mult(SEXP mat1SEXP, SEXP mat2SEXP, SEXP ISEXP, SEXP JSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type mat1(mat1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mat2(mat2SEXP);
    Rcpp::traits::input_parameter< int >::type I(ISEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(mat_mult(mat1, mat2, I, J, K));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_einsum_twice", (DL_FUNC) &_einsum_twice, 1},
    {"_einsum_einsum_impl_fast", (DL_FUNC) &_einsum_einsum_impl_fast, 5},
    {"_einsum_mat_mult", (DL_FUNC) &_einsum_mat_mult, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_einsum(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
